"use strict";
exports.__esModule = true;
var Circle_1 = require("./Circle");
var rectangle_1 = require("./rectangle");
var circleobj = new Circle_1.Circle(3);
circleobj.Myarea();
circleobj.Display();
var rectobj = new rectangle_1.Rectangle(2, 3);
rectobj.Myarea();
rectobj.Display();
